# Conclusion

Based on our analysis, we can draw several important conclusions. Firstly, our denoising algorithm is effective across all three variants. That is, by isolating signal generating components and cleaning them separately first before reconstruction and further cleaning works towards creating denoised spectrograms with high structural clarity and integrity. Furthermore, there is a clear structural difference between signal-present and signal-absent images. In the future, this project will see great value in exploring the potential of introducing signal-absent images that contain man-made interference that have a clear structural presence, thereby potentially changing our current opinion of the state of difference between whale-call having images and whale-call absent images. This approach however, is rather computationally intensive and limited, especially when more granular percentile intensities are proposed to clean the singular components. Hence a necessary direction of research will be that of exploring algorithm optimization for our solution. However, we reiterate the overall success of our algorithm, and highly encourage further customization and or exploration of the bioacoustic data universe using our denoising method.

